version: '2'

services:
  nginx-scitokens:
    build: .
    container_name: nginx-scitokens
    volumes:
      - ./certs/:/etc/letsencrypt
      - ./data:/data
    ports:
      - 80:80
      - 443:443